export const FETCH_OOMPA_LOOMPAS_REQUEST = 'FETCH_OOMPA_LOOMPAS_REQUEST';
export const FETCH_OOMPA_LOOMPAS_SUCCESS = 'FETCH_OOMPA_LOOMPAS_SUCCESS';
export const FETCH_OOMPA_LOOMPAS_FAILURE = 'FETCH_OOMPA_LOOMPAS_FAILURE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'; 

export const FETCH_OOMPA_DETAIL_REQUEST = 'FETCH_OOMPA_DETAIL_REQUEST';
export const FETCH_OOMPA_DETAIL_SUCCESS = 'FETCH_OOMPA_DETAIL_SUCCESS';
export const FETCH_OOMPA_DETAIL_FAILURE = 'FETCH_OOMPA_DETAIL_FAILURE';

